package ar.ncode.plugin.model;

public enum MessageId {

	HUD_CURRENT_ROLE_PREPARING,
	HUD_CURRENT_ROLE_SPECTATOR,
	HUD_CURRENT_ROLE_INNOCENT,
	HUD_CURRENT_ROLE_TRAITOR,
	HUD_CURRENT_ROLE_DETECTIVE,

	SCOREBOARD_TITLE,
	SCOREBOARD_TITLES_PLAYER,
	SCOREBOARD_TITLES_ROLE,
	SCOREBOARD_TITLES_KARMA,
	SCOREBOARD_TITLES_KILLS,
	SCOREBOARD_TITLES_DEATHS,
	SCOREBOARD_TITLES_PING,

	PLAYER_ASSIGNED_ROLE_NOTIFICATION,

	ROUND_ABOUT_TO_START_MSG,
	ROUND_START_MSG,
	ROUND_TRAITORS_WIN_MSG,
	ROUND_INNOCENTS_WIN_MSG,
	ROUND_TIME_FINISHED,

	THERE_ARE_NOT_ENOUGH_PLAYERS,

	SHOP_TITLE,
	SHOP_CREDITS,
	SHOP_BUY,
	SHOP_NOT_ENOUGH_CREDITS,
	SHOP_ITEM_BOUGHT,
	SHOP_NO_SPACE,
	SHOP_CLOSE,
	SHOP_ONLY_FOR_TRAITORS_OR_DETECTIVES,

	GRAVESTONE_PLATE_TITLE,
	GRAVESTONE_PLATE_PLAYER,
	GRAVESTONE_PLATE_ROLE,
	GRAVESTONE_PLATE_DEATH_TIME,
	GRAVESTONE_PLATE_DEATH_CAUSE,
	GRAVESTONE_PLATE_REPORT_DEATH,
	GRAVESTONE_PLATE_CLOSE,
	;

	public static final String LANG_FILE_NAME = "ncodeTTT";

	public String get() {
		return LANG_FILE_NAME + "." + this.name().toLowerCase();
	}
}
